[package]
name = "mitsu-ac"
version = "0.1.0"
authors = ["David Goodlad <david@goodlad.net>"]
edition = "2018"

[dependencies]
nom = { version = "^4.2", default-features = false }
embedded-hal = "0.2.2"
heapless = "0.4.3"
